section rodata_user
public _mysong
_mysong:
; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Start:
StartDisarkGenerateExternalLabel:

DisarkByteRegionStart0:
	db "AT20"
DisarkPointerRegionStart1:
	dw ArpeggioTable	; The address of the Arpeggio table.
	dw PitchTable	; The address of the Pitch table.
	dw InstrumentTable	; The address of the Instrument table.
	dw EffectBlockTable	; The address of the Effect Block table.
DisarkPointerRegionEnd1:


; The addresses of each Subsong:
DisarkPointerRegionStart2:
	dw Subsong0_Start
DisarkPointerRegionEnd2:

; Declares all the Arpeggios.
ArpeggioTable:
DisarkPointerRegionStart3:
DisarkPointerRegionEnd3:

; Declares all the Pitches.
PitchTable:
DisarkPointerRegionStart4:
DisarkPointerRegionEnd4:

; Declares all the Instruments.
InstrumentTable:
DisarkPointerRegionStart5:
	dw EmptyInstrument
	dw Instrument1
	dw Instrument2
DisarkPointerRegionEnd5:

EmptyInstrument:
	db 0	; The speed (>0, 0 for 256).
EmptyInstrument_Loop:	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Instrument1:
	db 5	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

Instrument2:
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
EffectBlockTable:
DisarkPointerRegionStart6:
	dw EffectBlock_P4P1	; Index 0
	dw EffectBlock_P4P2	; Index 1
DisarkPointerRegionEnd6:

EffectBlock_P4P1:
	db 4, 1
EffectBlock_P4P2:
	db 4, 2

DisarkByteRegionEnd0:

; Subsong 0
; ----------------------
Subsong0_DisarkByteRegionStart0:
Subsong0_Start:
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 88	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 29	; Base note index (>=0).

Subsong0_Linker:
Subsong0_DisarkPointerRegionStart1:
; Position 0
Subsong0_Linker_Loop:
	dw Subsong0_Track0
	dw Subsong0_Track1
	dw Subsong0_Track2
	dw Subsong0_LinkerBlock0

; Position 1
	dw Subsong0_Track4
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock1

; Position 2
	dw Subsong0_Track7
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock1

; Position 3
	dw Subsong0_Track4
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock1

; Position 4
	dw Subsong0_Track7
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock1

; Position 5
	dw Subsong0_Track4
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock1

; Position 6
	dw Subsong0_Track7
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock1

; Position 7
	dw Subsong0_Track7
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock1

; Position 8
	dw Subsong0_Track8
	dw Subsong0_Track9
	dw Subsong0_Track10
	dw Subsong0_LinkerBlock1

; Position 9
	dw Subsong0_Track11
	dw Subsong0_Track3
	dw Subsong0_Track12
	dw Subsong0_LinkerBlock1

; Position 10
	dw Subsong0_Track13
	dw Subsong0_Track3
	dw Subsong0_Track14
	dw Subsong0_LinkerBlock1

; Position 11
	dw Subsong0_Track15
	dw Subsong0_Track16
	dw Subsong0_Track17
	dw Subsong0_LinkerBlock1

; Position 12
	dw Subsong0_Track18
	dw Subsong0_Track19
	dw Subsong0_Track20
	dw Subsong0_LinkerBlock1

; Position 13
	dw Subsong0_Track21
	dw Subsong0_Track22
	dw Subsong0_Track23
	dw Subsong0_LinkerBlock1

; Position 14
	dw Subsong0_Track18
	dw Subsong0_Track24
	dw Subsong0_Track25
	dw Subsong0_LinkerBlock1

; Position 15
	dw Subsong0_Track26
	dw Subsong0_Track27
	dw Subsong0_Track28
	dw Subsong0_LinkerBlock1

; Position 16
	dw Subsong0_Track29
	dw Subsong0_Track30
	dw Subsong0_Track31
	dw Subsong0_LinkerBlock1

; Position 17
	dw Subsong0_Track32
	dw Subsong0_Track33
	dw Subsong0_Track31
	dw Subsong0_LinkerBlock1

; Position 18
	dw Subsong0_Track29
	dw Subsong0_Track34
	dw Subsong0_Track31
	dw Subsong0_LinkerBlock1

; Position 19
	dw Subsong0_Track35
	dw Subsong0_Track36
	dw Subsong0_Track37
	dw Subsong0_LinkerBlock1

; Position 20
	dw Subsong0_Track38
	dw Subsong0_Track3
	dw Subsong0_Track39
	dw Subsong0_LinkerBlock1

; Position 21
	dw Subsong0_Track13
	dw Subsong0_Track3
	dw Subsong0_Track14
	dw Subsong0_LinkerBlock1

; Position 22
	dw Subsong0_Track15
	dw Subsong0_Track40
	dw Subsong0_Track17
	dw Subsong0_LinkerBlock1

; Position 23
	dw Subsong0_Track18
	dw Subsong0_Track41
	dw Subsong0_Track20
	dw Subsong0_LinkerBlock1

; Position 24
	dw Subsong0_Track21
	dw Subsong0_Track42
	dw Subsong0_Track23
	dw Subsong0_LinkerBlock1

; Position 25
	dw Subsong0_Track18
	dw Subsong0_Track43
	dw Subsong0_Track25
	dw Subsong0_LinkerBlock1

; Position 26
	dw Subsong0_Track26
	dw Subsong0_Track44
	dw Subsong0_Track28
	dw Subsong0_LinkerBlock1

; Position 27
	dw Subsong0_Track29
	dw Subsong0_Track45
	dw Subsong0_Track31
	dw Subsong0_LinkerBlock1

; Position 28
	dw Subsong0_Track32
	dw Subsong0_Track46
	dw Subsong0_Track31
	dw Subsong0_LinkerBlock1

; Position 29
	dw Subsong0_Track29
	dw Subsong0_Track47
	dw Subsong0_Track31
	dw Subsong0_LinkerBlock1

; Position 30
	dw Subsong0_Track35
	dw Subsong0_Track48
	dw Subsong0_Track37
	dw Subsong0_LinkerBlock1

; Position 31
	dw Subsong0_Track49
	dw Subsong0_Track50
	dw Subsong0_Track3
	dw Subsong0_LinkerBlock1

; Position 32
	dw Subsong0_Track51
	dw Subsong0_Track52
	dw Subsong0_Track3
	dw Subsong0_LinkerBlock1

; Position 33
	dw Subsong0_Track53
	dw Subsong0_Track54
	dw Subsong0_Track3
	dw Subsong0_LinkerBlock1

; Position 34
	dw Subsong0_Track55
	dw Subsong0_Track56
	dw Subsong0_Track3
	dw Subsong0_LinkerBlock1

; Position 35
	dw Subsong0_Track57
	dw Subsong0_Track58
	dw Subsong0_Track59
	dw Subsong0_LinkerBlock1

; Position 36
	dw Subsong0_Track60
	dw Subsong0_Track61
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 37
	dw Subsong0_Track63
	dw Subsong0_Track64
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 38
	dw Subsong0_Track60
	dw Subsong0_Track65
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 39
	dw Subsong0_Track63
	dw Subsong0_Track66
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 40
	dw Subsong0_Track60
	dw Subsong0_Track67
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 41
	dw Subsong0_Track63
	dw Subsong0_Track68
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 42
	dw Subsong0_Track60
	dw Subsong0_Track69
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 43
	dw Subsong0_Track63
	dw Subsong0_Track70
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 44
	dw Subsong0_Track60
	dw Subsong0_Track71
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 45
	dw Subsong0_Track63
	dw Subsong0_Track72
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 46
	dw Subsong0_Track60
	dw Subsong0_Track73
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 47
	dw Subsong0_Track63
	dw Subsong0_Track74
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 48
	dw Subsong0_Track60
	dw Subsong0_Track75
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 49
	dw Subsong0_Track63
	dw Subsong0_Track76
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 50
	dw Subsong0_Track60
	dw Subsong0_Track77
	dw Subsong0_Track62
	dw Subsong0_LinkerBlock1

; Position 51
	dw Subsong0_Track78
	dw Subsong0_Track79
	dw Subsong0_Track80
	dw Subsong0_LinkerBlock1

; Position 52
	dw Subsong0_Track81
	dw Subsong0_Track82
	dw Subsong0_Track3
	dw Subsong0_LinkerBlock1

; Position 53
	dw Subsong0_Track83
	dw Subsong0_Track84
	dw Subsong0_Track3
	dw Subsong0_LinkerBlock1

; Position 54
	dw Subsong0_Track85
	dw Subsong0_Track86
	dw Subsong0_Track3
	dw Subsong0_LinkerBlock1

; Position 55
	dw Subsong0_Track87
	dw Subsong0_Track88
	dw Subsong0_Track3
	dw Subsong0_LinkerBlock1

; Position 56
	dw Subsong0_Track89
	dw Subsong0_Track3
	dw Subsong0_Track90
	dw Subsong0_LinkerBlock1

; Position 57
	dw Subsong0_Track91
	dw Subsong0_Track3
	dw Subsong0_Track92
	dw Subsong0_LinkerBlock1

; Position 58
	dw Subsong0_Track93
	dw Subsong0_Track94
	dw Subsong0_Track95
	dw Subsong0_LinkerBlock1

; Position 59
	dw Subsong0_Track96
	dw Subsong0_Track97
	dw Subsong0_Track98
	dw Subsong0_LinkerBlock1

; Position 60
	dw Subsong0_Track99
	dw Subsong0_Track100
	dw Subsong0_Track101
	dw Subsong0_LinkerBlock1

; Position 61
	dw Subsong0_Track102
	dw Subsong0_Track103
	dw Subsong0_Track104
	dw Subsong0_LinkerBlock1

; Position 62
	dw Subsong0_Track105
	dw Subsong0_Track106
	dw Subsong0_Track107
	dw Subsong0_LinkerBlock1

; Position 63
	dw Subsong0_Track108
	dw Subsong0_Track109
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 64
	dw Subsong0_Track111
	dw Subsong0_Track112
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 65
	dw Subsong0_Track108
	dw Subsong0_Track113
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 66
	dw Subsong0_Track114
	dw Subsong0_Track115
	dw Subsong0_Track116
	dw Subsong0_LinkerBlock1

; Position 67
	dw Subsong0_Track117
	dw Subsong0_Track3
	dw Subsong0_Track90
	dw Subsong0_LinkerBlock1

; Position 68
	dw Subsong0_Track91
	dw Subsong0_Track3
	dw Subsong0_Track92
	dw Subsong0_LinkerBlock1

; Position 69
	dw Subsong0_Track93
	dw Subsong0_Track118
	dw Subsong0_Track95
	dw Subsong0_LinkerBlock1

; Position 70
	dw Subsong0_Track96
	dw Subsong0_Track119
	dw Subsong0_Track98
	dw Subsong0_LinkerBlock1

; Position 71
	dw Subsong0_Track99
	dw Subsong0_Track120
	dw Subsong0_Track101
	dw Subsong0_LinkerBlock1

; Position 72
	dw Subsong0_Track102
	dw Subsong0_Track121
	dw Subsong0_Track104
	dw Subsong0_LinkerBlock1

; Position 73
	dw Subsong0_Track105
	dw Subsong0_Track122
	dw Subsong0_Track107
	dw Subsong0_LinkerBlock1

; Position 74
	dw Subsong0_Track108
	dw Subsong0_Track123
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 75
	dw Subsong0_Track111
	dw Subsong0_Track124
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 76
	dw Subsong0_Track108
	dw Subsong0_Track125
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 77
	dw Subsong0_Track111
	dw Subsong0_Track126
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 78
	dw Subsong0_Track108
	dw Subsong0_Track123
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 79
	dw Subsong0_Track111
	dw Subsong0_Track124
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 80
	dw Subsong0_Track108
	dw Subsong0_Track125
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 81
	dw Subsong0_Track111
	dw Subsong0_Track126
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 82
	dw Subsong0_Track108
	dw Subsong0_Track123
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 83
	dw Subsong0_Track111
	dw Subsong0_Track124
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 84
	dw Subsong0_Track108
	dw Subsong0_Track125
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 85
	dw Subsong0_Track111
	dw Subsong0_Track126
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 86
	dw Subsong0_Track108
	dw Subsong0_Track123
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 87
	dw Subsong0_Track111
	dw Subsong0_Track124
	dw Subsong0_Track110
	dw Subsong0_LinkerBlock1

; Position 88
	dw Subsong0_Track127
	dw Subsong0_Track128
	dw Subsong0_Track129
	dw Subsong0_LinkerBlock1

Subsong0_DisarkPointerRegionEnd1:
	dw 0	; Loop.
Subsong0_DisarkWordForceReference2:
	dw Subsong0_Linker_Loop

Subsong0_LinkerBlock0:
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong0_DisarkWordForceReference3:
	dw Subsong0_SpeedTrack0	; SpeedTrack address.
Subsong0_DisarkWordForceReference4:
	dw Subsong0_EventTrack0	; EventTrack address.
Subsong0_LinkerBlock1:
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong0_DisarkWordForceReference5:
	dw Subsong0_SpeedTrack1	; SpeedTrack address.
Subsong0_DisarkWordForceReference6:
	dw Subsong0_EventTrack0	; EventTrack address.

Subsong0_Track0:
	db 208
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 23
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 21
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 21
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 13
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 23
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 61, 127	; Waits for 128 lines.


Subsong0_Track1:
	db 232
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 37
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 61, 127	; Waits for 128 lines.


Subsong0_Track2:
	db 232
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 37
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 61, 127	; Waits for 128 lines.


Subsong0_Track3:
	db 61, 127	; Waits for 128 lines.


Subsong0_Track4:
	db 144
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 23
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 21
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 21
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 13
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 23
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 13
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 15
	db 61, 127	; Waits for 128 lines.


Subsong0_Track5:
	db 168
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 37
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 61, 127	; Waits for 128 lines.


Subsong0_Track6:
	db 168
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 37
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 61, 127	; Waits for 128 lines.


Subsong0_Track7:
	db 144
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 23
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 21
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 21
	db 60	; Waits for 1 line.

	db 14
	db 60	; Waits for 1 line.

	db 13
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 23
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 61, 127	; Waits for 128 lines.


Subsong0_Track8:
	db 61, 29	; Waits for 30 lines.

	db 139
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track9:
	db 173
	db 1	; New Instrument (1).
	db 47
	db 50
	db 60	; Waits for 1 line.

	db 47
	db 50
	db 52
	db 60	; Waits for 1 line.

	db 50
	db 52
	db 54
	db 60	; Waits for 1 line.

	db 52
	db 54
	db 63
	db 86	; Escape note (86).
	db 60	; Waits for 1 line.

	db 54
	db 63
	db 86	; Escape note (86).
	db 63
	db 88	; Escape note (88).
	db 60	; Waits for 1 line.

	db 63
	db 86	; Escape note (86).
	db 63
	db 88	; Escape note (88).
	db 63
	db 91	; Escape note (91).
	db 60	; Waits for 1 line.

	db 63
	db 93	; Escape note (93).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 47
	db 61, 127	; Waits for 128 lines.


Subsong0_Track10:
	db 61, 29	; Waits for 30 lines.

	db 173
	db 2	; New Instrument (2).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track11:
	db 61, 17	; Waits for 18 lines.

	db 134
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 1
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 3
	db 60	; Waits for 1 line.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track12:
	db 61, 31	; Waits for 32 lines.

	db 168
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track13:
	db 132
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track14:
	db 168
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track15:
	db 132
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track16:
	db 61, 31	; Waits for 32 lines.

	db 239
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


Subsong0_Track17:
	db 168
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 99
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track18:
	db 130
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 60	; Waits for 1 line.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 60	; Waits for 1 line.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 60	; Waits for 1 line.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 61, 127	; Waits for 128 lines.


Subsong0_Track19:
	db 173
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 61, 18	; Waits for 19 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 61, 127	; Waits for 128 lines.


Subsong0_Track20:
	db 166
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 61, 127	; Waits for 128 lines.


Subsong0_Track21:
	db 132
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 60	; Waits for 1 line.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track22:
	db 168
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 60	; Waits for 1 line.

	db 40
	db 61, 20	; Waits for 21 lines.

	db 45
	db 46
	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


Subsong0_Track23:
	db 163
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track24:
	db 172
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 61, 18	; Waits for 19 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 61, 127	; Waits for 128 lines.


Subsong0_Track25:
	db 166
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 60	; Waits for 1 line.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 61, 127	; Waits for 128 lines.


Subsong0_Track26:
	db 132
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 61, 14	; Waits for 15 lines.

	db 0
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 61, 127	; Waits for 128 lines.


Subsong0_Track27:
	db 170
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 61, 18	; Waits for 19 lines.

	db 178
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 61, 8	; Waits for 9 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 61, 127	; Waits for 128 lines.


Subsong0_Track28:
	db 163
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 35
	db 61, 6	; Waits for 7 lines.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 61, 14	; Waits for 15 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 61, 127	; Waits for 128 lines.


Subsong0_Track29:
	db 132
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 61, 127	; Waits for 128 lines.


Subsong0_Track30:
	db 173
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 61, 22	; Waits for 23 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 61, 127	; Waits for 128 lines.


Subsong0_Track31:
	db 168
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 61, 127	; Waits for 128 lines.


Subsong0_Track32:
	db 132
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 18
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 61, 127	; Waits for 128 lines.


Subsong0_Track33:
	db 182
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 52
	db 61, 18	; Waits for 19 lines.

	db 50
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 61, 8	; Waits for 9 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 61, 127	; Waits for 128 lines.


Subsong0_Track34:
	db 173
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 61, 14	; Waits for 15 lines.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 61, 127	; Waits for 128 lines.


Subsong0_Track35:
	db 132
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 18
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track36:
	db 182
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 52
	db 61, 127	; Waits for 128 lines.


Subsong0_Track37:
	db 168
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


Subsong0_Track38:
	db 61, 31	; Waits for 32 lines.

	db 132
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track39:
	db 61, 31	; Waits for 32 lines.

	db 232
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track40:
	db 61, 29	; Waits for 30 lines.

	db 223
	db 2	; New Instrument (2).
	db 1	; Index to an effect block.
	db 34
	db 111
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


Subsong0_Track41:
	db 173
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 61, 18	; Waits for 19 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 61, 127	; Waits for 128 lines.


Subsong0_Track42:
	db 168
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 60	; Waits for 1 line.

	db 40
	db 61, 21	; Waits for 22 lines.

	db 46
	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


Subsong0_Track43:
	db 172
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 61, 18	; Waits for 19 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 61, 127	; Waits for 128 lines.


Subsong0_Track44:
	db 170
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 61, 18	; Waits for 19 lines.

	db 178
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 61, 8	; Waits for 9 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 61, 127	; Waits for 128 lines.


Subsong0_Track45:
	db 173
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 61, 22	; Waits for 23 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 61, 127	; Waits for 128 lines.


Subsong0_Track46:
	db 182
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 52
	db 61, 18	; Waits for 19 lines.

	db 50
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 61, 8	; Waits for 9 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 61, 127	; Waits for 128 lines.


Subsong0_Track47:
	db 173
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 47
	db 60	; Waits for 1 line.

	db 43
	db 61, 14	; Waits for 15 lines.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 61, 127	; Waits for 128 lines.


Subsong0_Track48:
	db 182
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 52
	db 61, 127	; Waits for 128 lines.


Subsong0_Track49:
	db 61, 33	; Waits for 34 lines.

	db 132
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 61, 127	; Waits for 128 lines.


Subsong0_Track50:
	db 61, 33	; Waits for 34 lines.

	db 220
	db 1	; New Instrument (1).
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track51:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 144
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 21
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 23
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 27
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 61, 127	; Waits for 128 lines.


Subsong0_Track52:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 168
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 51
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 61, 127	; Waits for 128 lines.


Subsong0_Track53:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 61, 14	; Waits for 15 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 61, 6	; Waits for 7 lines.

	db 4
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track54:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 164
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 61, 6	; Waits for 7 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 61, 14	; Waits for 15 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 61, 6	; Waits for 7 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track55:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 128
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 61, 14	; Waits for 15 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 61, 6	; Waits for 7 lines.

	db 4
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 11
	db 61, 127	; Waits for 128 lines.


Subsong0_Track56:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 164
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 61, 6	; Waits for 7 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 61, 14	; Waits for 15 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 61, 6	; Waits for 7 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 42
	db 61, 127	; Waits for 128 lines.


Subsong0_Track57:
	db 61, 47	; Waits for 48 lines.

	db 191
	db 28	; Escape note (28).
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track58:
	db 61, 61	; Waits for 62 lines.

	db 179
	db 2	; New Instrument (2).
	db 52
	db 61, 127	; Waits for 128 lines.


Subsong0_Track59:
	db 61, 61	; Waits for 62 lines.

	db 163
	db 2	; New Instrument (2).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track60:
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 139
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 11
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 60	; Waits for 1 line.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 7
	db 60	; Waits for 1 line.

	db 9
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 60	; Waits for 1 line.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 21
	db 60	; Waits for 1 line.

	db 21
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 60	; Waits for 1 line.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track61:
	db 180
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 52
	db 52
	db 52
	db 60	; Waits for 1 line.

	db 52
	db 52
	db 52
	db 60	; Waits for 1 line.

	db 52
	db 52
	db 52
	db 60	; Waits for 1 line.

	db 52
	db 52
	db 52
	db 60	; Waits for 1 line.

	db 52
	db 52
	db 52
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 61, 6	; Waits for 7 lines.

	db 54
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 52
	db 61, 14	; Waits for 15 lines.

	db 50
	db 51
	db 52
	db 60	; Waits for 1 line.

	db 52
	db 52
	db 61, 127	; Waits for 128 lines.


Subsong0_Track62:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 159
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 61, 127	; Waits for 128 lines.


Subsong0_Track63:
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 139
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 11
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 60	; Waits for 1 line.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 7
	db 60	; Waits for 1 line.

	db 9
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 60	; Waits for 1 line.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 21
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 21
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 60	; Waits for 1 line.

	db 15
	db 60	; Waits for 1 line.

	db 16
	db 60	; Waits for 1 line.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track64:
	db 180
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 52
	db 52
	db 52
	db 60	; Waits for 1 line.

	db 52
	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 51
	db 50
	db 60	; Waits for 1 line.

	db 52
	db 52
	db 52
	db 60	; Waits for 1 line.

	db 52
	db 52
	db 52
	db 60	; Waits for 1 line.

	db 52
	db 52
	db 52
	db 60	; Waits for 1 line.

	db 52
	db 52
	db 54
	db 60	; Waits for 1 line.

	db 55
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 54
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 52
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 63
	db 86	; Escape note (86).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 86	; Escape note (86).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 86	; Escape note (86).
	db 60	; Waits for 1 line.

	db 63
	db 87	; Escape note (87).
	db 60	; Waits for 1 line.

	db 63
	db 88	; Escape note (88).
	db 60	; Waits for 1 line.

	db 63
	db 91	; Escape note (91).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track65:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 191
	db 93	; Escape note (93).
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 63
	db 88	; Escape note (88).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 91	; Escape note (91).
	db 60	; Waits for 1 line.

	db 63
	db 93	; Escape note (93).
	db 60	; Waits for 1 line.

	db 63
	db 88	; Escape note (88).
	db 60	; Waits for 1 line.

	db 63
	db 88	; Escape note (88).
	db 60	; Waits for 1 line.

	db 63
	db 86	; Escape note (86).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 86	; Escape note (86).
	db 60	; Waits for 1 line.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 55
	db 55
	db 55
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 54
	db 60	; Waits for 1 line.

	db 54
	db 54
	db 54
	db 60	; Waits for 1 line.

	db 54
	db 60	; Waits for 1 line.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 50
	db 50
	db 60	; Waits for 1 line.

	db 45
	db 61, 127	; Waits for 128 lines.


Subsong0_Track66:
	db 178
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 52
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 50
	db 50
	db 60	; Waits for 1 line.

	db 52
	db 52
	db 52
	db 60	; Waits for 1 line.

	db 54
	db 54
	db 54
	db 60	; Waits for 1 line.

	db 55
	db 55
	db 55
	db 60	; Waits for 1 line.

	db 63
	db 86	; Escape note (86).
	db 63
	db 86	; Escape note (86).
	db 63
	db 88	; Escape note (88).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track67:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 166
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 35
	db 35
	db 35
	db 60	; Waits for 1 line.

	db 35
	db 35
	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 42
	db 42
	db 60	; Waits for 1 line.

	db 42
	db 42
	db 42
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track68:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 168
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 60	; Waits for 1 line.

	db 46
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 47
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 63
	db 88	; Escape note (88).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track69:
	db 175
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 43
	db 44
	db 60	; Waits for 1 line.

	db 45
	db 45
	db 45
	db 60	; Waits for 1 line.

	db 45
	db 45
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 42
	db 40
	db 43
	db 60	; Waits for 1 line.

	db 42
	db 52
	db 43
	db 60	; Waits for 1 line.

	db 42
	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 38
	db 38
	db 38
	db 60	; Waits for 1 line.

	db 40
	db 40
	db 40
	db 60	; Waits for 1 line.

	db 40
	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track70:
	db 168
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 40
	db 40
	db 40
	db 60	; Waits for 1 line.

	db 40
	db 40
	db 40
	db 60	; Waits for 1 line.

	db 40
	db 40
	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 60	; Waits for 1 line.

	db 26
	db 26
	db 26
	db 60	; Waits for 1 line.

	db 26
	db 26
	db 26
	db 61, 127	; Waits for 128 lines.


Subsong0_Track71:
	db 156
	db 2	; New Instrument (2).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 60	; Waits for 1 line.

	db 23
	db 60	; Waits for 1 line.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 23
	db 60	; Waits for 1 line.

	db 26
	db 28
	db 30
	db 60	; Waits for 1 line.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 33
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 36
	db 60	; Waits for 1 line.

	db 36
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 33
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 61, 127	; Waits for 128 lines.


Subsong0_Track72:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 168
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 61, 127	; Waits for 128 lines.


Subsong0_Track73:
	db 168
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 50
	db 50
	db 50
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 54
	db 60	; Waits for 1 line.

	db 52
	db 61, 127	; Waits for 128 lines.


Subsong0_Track74:
	db 180
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 38
	db 61, 127	; Waits for 128 lines.


Subsong0_Track75:
	db 61, 5	; Waits for 6 lines.

	db 168
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 60	; Waits for 1 line.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track76:
	db 61, 5	; Waits for 6 lines.

	db 170
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 49
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 46
	db 61, 127	; Waits for 128 lines.


Subsong0_Track77:
	db 175
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 46
	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 46
	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 46
	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 46
	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 47
	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 61, 127	; Waits for 128 lines.


Subsong0_Track78:
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 139
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 11
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 60	; Waits for 1 line.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 7
	db 60	; Waits for 1 line.

	db 9
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 60	; Waits for 1 line.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 21
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 60	; Waits for 1 line.

	db 20
	db 60	; Waits for 1 line.

	db 21
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 60	; Waits for 1 line.

	db 15
	db 60	; Waits for 1 line.

	db 16
	db 61, 127	; Waits for 128 lines.


Subsong0_Track79:
	db 171
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 42
	db 42
	db 42
	db 60	; Waits for 1 line.

	db 42
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 40
	db 40
	db 60	; Waits for 1 line.

	db 38
	db 38
	db 38
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 37
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 40
	db 40
	db 60	; Waits for 1 line.

	db 40
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 42
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track80:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 159
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 37
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 35
	db 61, 127	; Waits for 128 lines.


Subsong0_Track81:
	db 132
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 21
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 23
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 26
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 27
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 28
	db 61, 127	; Waits for 128 lines.


Subsong0_Track82:
	db 156
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 51
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 61, 127	; Waits for 128 lines.


Subsong0_Track83:
	db 61, 31	; Waits for 32 lines.

	db 128
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 61, 127	; Waits for 128 lines.


Subsong0_Track84:
	db 61, 31	; Waits for 32 lines.

	db 176
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 61, 127	; Waits for 128 lines.


Subsong0_Track85:
	db 130
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 61, 6	; Waits for 7 lines.

	db 4
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 14	; Waits for 15 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 61, 127	; Waits for 128 lines.


Subsong0_Track86:
	db 178
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 61, 14	; Waits for 15 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 61, 127	; Waits for 128 lines.


Subsong0_Track87:
	db 130
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 61, 6	; Waits for 7 lines.

	db 4
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 11
	db 61, 127	; Waits for 128 lines.


Subsong0_Track88:
	db 178
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 52
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 61, 6	; Waits for 7 lines.

	db 47
	db 61, 127	; Waits for 128 lines.


Subsong0_Track89:
	db 61, 13	; Waits for 14 lines.

	db 191
	db 28	; Escape note (28).
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 63
	db 28	; Escape note (28).
	db 60	; Waits for 1 line.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track90:
	db 61, 27	; Waits for 28 lines.

	db 232
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track91:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 132
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track92:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 168
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track93:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 132
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 60	; Waits for 1 line.

	db 2
	db 61, 127	; Waits for 128 lines.


Subsong0_Track94:
	db 61, 27	; Waits for 28 lines.

	db 239
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


Subsong0_Track95:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 168
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 99
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 61, 127	; Waits for 128 lines.


Subsong0_Track96:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 137
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 9
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 60	; Waits for 1 line.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 60	; Waits for 1 line.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 60	; Waits for 1 line.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 60	; Waits for 1 line.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track97:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 170
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 61, 18	; Waits for 19 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track98:
	db 166
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 60	; Waits for 1 line.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 61, 127	; Waits for 128 lines.


Subsong0_Track99:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 135
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 7
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 60	; Waits for 1 line.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 60	; Waits for 1 line.

	db 2
	db 61, 127	; Waits for 128 lines.


Subsong0_Track100:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 170
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 40
	db 61, 20	; Waits for 21 lines.

	db 45
	db 46
	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 44
	db 61, 127	; Waits for 128 lines.


Subsong0_Track101:
	db 168
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 61, 127	; Waits for 128 lines.


Subsong0_Track102:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 137
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 9
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 60	; Waits for 1 line.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 60	; Waits for 1 line.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 14
	db 60	; Waits for 1 line.

	db 14
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 60	; Waits for 1 line.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track103:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 170
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 61, 18	; Waits for 19 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 42
	db 61, 127	; Waits for 128 lines.


Subsong0_Track104:
	db 166
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 40
	db 60	; Waits for 1 line.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 60	; Waits for 1 line.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 35
	db 60	; Waits for 1 line.

	db 35
	db 61, 127	; Waits for 128 lines.


Subsong0_Track105:
	db 132
	db 1	; New Instrument (1).
	db 61, 6	; Waits for 7 lines.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 61, 14	; Waits for 15 lines.

	db 0
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track106:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 168
	db 1	; New Instrument (1).
	db 61, 18	; Waits for 19 lines.

	db 178
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 61, 8	; Waits for 9 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


Subsong0_Track107:
	db 163
	db 2	; New Instrument (2).
	db 61, 6	; Waits for 7 lines.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 61, 14	; Waits for 15 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track108:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 139
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 18
	db 60	; Waits for 1 line.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track109:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 175
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 43
	db 61, 22	; Waits for 23 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 61, 127	; Waits for 128 lines.


Subsong0_Track110:
	db 171
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track111:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 139
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 18
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 7
	db 60	; Waits for 1 line.

	db 7
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 0
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 9
	db 60	; Waits for 1 line.

	db 9
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track112:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 180
	db 2	; New Instrument (2).
	db 61, 18	; Waits for 19 lines.

	db 50
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 61, 8	; Waits for 9 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


Subsong0_Track113:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 175
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 43
	db 61, 14	; Waits for 15 lines.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 61, 127	; Waits for 128 lines.


Subsong0_Track114:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 139
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 18
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track115:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 180
	db 2	; New Instrument (2).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track116:
	db 171
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 60	; Waits for 1 line.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


Subsong0_Track117:
	db 61, 27	; Waits for 28 lines.

	db 132
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 2
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track118:
	db 61, 25	; Waits for 26 lines.

	db 223
	db 2	; New Instrument (2).
	db 1	; Index to an effect block.
	db 34
	db 111
	db 0	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


Subsong0_Track119:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 170
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 61, 18	; Waits for 19 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 40
	db 61, 127	; Waits for 128 lines.


Subsong0_Track120:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 170
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 40
	db 61, 21	; Waits for 22 lines.

	db 46
	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 44
	db 61, 127	; Waits for 128 lines.


Subsong0_Track121:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 170
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 38
	db 61, 18	; Waits for 19 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 42
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 35
	db 60	; Waits for 1 line.

	db 38
	db 60	; Waits for 1 line.

	db 42
	db 61, 127	; Waits for 128 lines.


Subsong0_Track122:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 168
	db 2	; New Instrument (2).
	db 61, 18	; Waits for 19 lines.

	db 178
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 61, 8	; Waits for 9 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


Subsong0_Track123:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 175
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 43
	db 61, 22	; Waits for 23 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 61, 127	; Waits for 128 lines.


Subsong0_Track124:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 180
	db 1	; New Instrument (1).
	db 61, 18	; Waits for 19 lines.

	db 50
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 61, 8	; Waits for 9 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


Subsong0_Track125:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 175
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 43
	db 61, 14	; Waits for 15 lines.

	db 45
	db 60	; Waits for 1 line.

	db 47
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 61, 6	; Waits for 7 lines.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 61, 127	; Waits for 128 lines.


Subsong0_Track126:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 180
	db 1	; New Instrument (1).
	db 61, 24	; Waits for 25 lines.

	db 48
	db 61, 8	; Waits for 9 lines.

	db 50
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 52
	db 60	; Waits for 1 line.

	db 50
	db 61, 6	; Waits for 7 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


Subsong0_Track127:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 139
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 11
	db 60	; Waits for 1 line.

	db 16
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 11
	db 61, 127	; Waits for 128 lines.


Subsong0_Track128:
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 175
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 43
	db 61, 127	; Waits for 128 lines.


Subsong0_Track129:
	db 171
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 40
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Subsong0_SpeedTrack0:
	db 6	; Value: 3.
	db 253	; Wait for 127 lines.
Subsong0_SpeedTrack1:
	db 255	; Wait for 128 lines.

; The event tracks
Subsong0_EventTrack0:
	db 255	; Wait for 128 lines.

Subsong0_DisarkByteRegionEnd0:
